### ISSUE TITLE
Mailer

### ISSUE THREAD

**Issue by ghost** [simplesoft-pt/Hosting#2]
Good day,

Could you add mail functionality where you can receive daily mails and log files sent to you?

**Comment by gravity00** [comment]
Hi @nicotravassos I'm not understanding your suggestion. Could you please elaborate?

**Comment by ghost** [comment]
My apologies I thought this application had another purposes for example checking the status of of services running and sending an email when service has stopped.

**Comment by gravity00** [comment]
@nicotravassos ah, I see, maybe that was influenced by the article I wrote in which the [example was something similar to what you mention](https://www.codeproject.com/Articles/1207983/Creating-Advanced-Console-Applications-in-NET). No need to apology!

But I can tell you that I'm using a similar implementation to monitor some APIs we have distributed over 3000 of our clients servers to ensure the applications are running and we are using NLog and custom targets to send us the data we may need. So, that's a requirement you may be able to solve without too much coding using this library and a good logger implementation.

**Comment by ghost** [comment]
Thanks @gravity00
